// Generated by CoffeeScript 1.9.3
var compile, create_scope, define_variable, delete_scope, update_variable;

this.resize_list = [];

define_variable = function(type, scp, name, val, id) {
  var scope, variable;
  if (id == null) {
    id = scp + "-" + name;
  }
  scope = $('#' + scp + " .scp");
  console.log(scope);
  scope.append('<div id=\'' + id + '\'></div>');
  variable = $('#' + id);
  console.log(variable);
  variable.append('<div class=\'tagTop\'></div>');
  variable.append('<div class=\'tagBot\'></div>');
  variable.children('.tagBot').html(val);
  variable.children('.tagTop').append('<div class="name"></div>');
  variable.children('.tagTop').append('<div class="type"></div>');
  variable.children('.tagTop').children('.name').html(name);
  variable.children('.tagTop').children('.type').html(type);
  variable.addClass('newborn');
  return setTimeout((function() {
    return variable.addClass('var').removeClass('newborn');
  }), 10);
};

update_variable = function(id, val) {
  var variable;
  variable = $('#' + id);
  return variable.children('.tagBot').html(val);
};

create_scope = function(scp, id) {
  var l;
  l = $('.var').length;
  $('#' + scp).append('<div id="' + id + '" class="scope"></div>');
  $('#' + id).append('<div class="banner">' + id + '</div>');
  $('#' + id).append('<div class="scp"></div>');
  $('#' + id).css('border', 'solid 1px black');
  return $('#' + id).css('border-radius', '10px');
};

delete_scope = function(id) {
  return $('#' + id).remove();
};

$('#ace1').ready(function() {
  var k, str;
  editor.resize(true);
  editor.setTheme("ace/theme/tomorrow_night_bright");
  editor.getSession().setMode("ace/mode/c_cpp");
  editor.setAutoScrollEditorIntoView(true);
  editor.setHighlightActiveLine(true);
  str = editor.getValue();
  return k = hljs.highlightAuto(str);
});

compile = function() {
  var code, input;
  code = editor.getValue();
  input = $('#stdin').val();
  code = window.btoa(code);
  input = window.btoa(input);
  return $.get("compile.php", {
    "code": code,
    "input": input
  }, function(obj) {
    return $('#stdout').val(obj);
  });
};
