// Generated by CoffeeScript 1.9.3
var add, define_variable;

define_variable = function(type, scp, name, val, id) {
  var scope, variable;
  scope = $('#' + scp);
  scope.append('<div id=\'' + id + '\'></div>');
  variable = $('#' + id);
  variable.append('<div class=\'tagTop\'></div>');
  variable.append('<div class=\'tagBot\'></div>');
  variable.children('.tagBot').html(val);
  variable.children('.tagTop').append('<div class="name"></div>');
  variable.children('.tagTop').append('<div class="type"></div>');
  variable.children('.tagTop').children('.name').html(name);
  variable.children('.tagTop').children('.type').html(type);
  variable.addClass('newborn');
  return setTimeout((function() {
    return variable.addClass('var').removeClass('newborn');
  }), 10);
};

$(function() {
  return define_variable('int', 'global', 'a', 32, 'global_a');
});

$(function() {
  return define_variable('int', 'global', 'b', 32, 'global_b');
});

add = function() {
  return define_variable($('#getT').val(), $('#getS').val(), $('#getN').val(), $('#getV').val(), $('#getI').val());
};
